# Use `clang` as the linker and `mold` for faster linking
[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

# Enable `sccache` for compiler caching
[build]
rustc-wrapper = "sccache"

# Optimize debug builds for faster compile times
[profile.dev]
codegen-units = 256  # Parallelize compilation (reduces optimizations)
codegen-backend = "cranelift"
lto = false          # Disable Link-Time Optimization for speed