[package]
name = "elytra-logger"
version.workspace = true
edition.workspace = true

[dependencies]
libc = { workspace = true }
windows-sys = { workspace = true }
once_cell = { workspace = true }

elytra-wotra = { path = "../elytra-wotra" }

[dev-dependencies]
assert_matches = { workspace = true } 