[package]
name = "elytra-common"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true } 